services:
  php:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www/html
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.hostel.rule=Host(`hostelcampus.com`) || Host(`www.hostelcampus.com`)"
      - "traefik.http.routers.hostel.entrypoints=web"
      - "traefik.http.services.hostel.loadbalancer.server.port=8000"
networks:
  default:
    external: true
    name: traefik