services:
  app:
    image: php:8.2-apache

    container_name: hostel-app

    ports:
      - "8000:80"

    volumes:
      - ./:/var/www/html

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.hostel.rule=Host(`hostelcampus.com`)"
      - "traefik.http.routers.hostel.entrypoints=web"
      - "traefik.http.services.hostel.loadbalancer.server.port=80"

    networks:
      - traefik

networks:
  traefik:
    external: true